Fix/search list many orgs modal
vtex-apps/b2b-organizations pull request #164
Opened 2024-07-03 13:25 UTC by Josmar-jr

#### What problem is this solving?

Before, it was not possible to filter the organization according to the value entered in the input at change organization modal

#### How to test it?

1. Navigate to [Workspace](https://josmarjr--b2bstore005.myvtex.com/admin/b2b-organizations/organizations#/organizations)
2. Select the settings option in tabs
3. Enable "Usar modal para trocar de organização"
4. Navigate to [Workspace](https://josmarjr--b2bstore005.myvtex.com/)
5. Do the login
6. Click on the button "Mudar organização"
7. Dispatch a new search at input

[Workspace](https://josmarjr--b2bstore005.myvtex.com/)

#### Screenshots or example usage:
<img width="1440" alt="Screenshot 2024-07-03 at 10 24 01" src="https://github.com/vtex-apps/b2b-organizations/assets/72118355/6e7c9c05-6620-46fd-9cf8-bd7d46557c58">
<img width="1440" alt="Screenshot 2024-07-03 at 10 23 46" src="https://github.com/vtex-apps/b2b-organizations/assets/72118355/bc445f0a-ea0b-4952-873b-254a10761b8c">

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2024-07-09 16:26 UTC, ArthurTriis1 commented on react/components/UserWidget.tsx
> +  }
```suggestion
  const handleSearchOrganizations = (e: any) => {
    const { value }: { value: string } = e.target
    let dataList

    setSearchTerm(e.target.value)
    
    dataList = userWidgetData?.getOrganizationsByEmail?.sort(
        sortOrganizations
      )

    if (value.trim() != '') {
        dataList =
        userWidgetData?.getOrganizationsByEmail
          ?.filter((organization: any) => {
            return (
              organization.organizationName
                .toLowerCase()
                .includes(value.toLowerCase()) ||
              organization.costCenterName
                .toLowerCase()
                .includes(value.toLowerCase())
            )
          })
          ?.slice(0, 15) ?? []
    }

    setOrganizationsState({
      ...organizationsState,
      dataList,
      totalDataList: dataList?.length,
    })
  }
```

2024-07-09 16:30 UTC, ArthurTriis1 reviewed
I tried to reproduce the issue and enabled the modal in the admin panel.

![Screenshot 2024-07-09 at 13 24 13](https://github.com/vtex-apps/b2b-organizations/assets/51174217/14db248d-1cc3-4294-8a78-1e8017c0e762)

However, the modal button does not appear.

![Screenshot 2024-07-09 at 13 23 02](https://github.com/vtex-apps/b2b-organizations/assets/51174217/156e8a6f-df20-4533-ae1d-4fc8f7d175f8)

Is there anything else I need to configure?

2024-07-11 14:28 UTC, Josmar-jr commented
@ArthurTriis1 just enabling the modal should work

2024-07-12 12:49 UTC, ArthurTriis1 commented
> @ArthurTriis1 just enabling the modal should work

Ok, I will try again, but the current workspace is broken, can you fix it?
![Screenshot 2024-07-12 at 09 49 22](https://github.com/user-attachments/assets/41da653a-cda9-4c54-b4e3-c96d22df0900)

2024-07-12 13:13 UTC, Josmar-jr commented
@ArthurTriis1 Here it is working normally. Please check if the project branch is up to date
<img width="1435" alt="Screenshot 2024-07-12 at 10 09 47" src="https://github.com/user-attachments/assets/223186a4-9991-41d5-ba0d-8cc72232262e">
<img width="1438" alt="Screenshot 2024-07-12 at 10 11 04" src="https://github.com/user-attachments/assets/0b102743-bacb-499c-aed9-8e3e0e8b4040">

2024-07-12 13:17 UTC, ArthurTriis1 commented
> @ArthurTriis1 Here it is working normally. Please check if the project branch is up to date 

It is working now! And I could test the modal, it is working fine!

2024-07-12 13:19 UTC, ArthurTriis1 approved these changes

2024-07-17 11:57 UTC, ArthurTriis1 requested changes

2024-07-17 11:57 UTC, ArthurTriis1 commented on CHANGELOG.md
> -
Some changes are being removed from the changelog, which is causing the checks to break. Could you please add those changes back and update the changelog?

2024-07-17 15:02 UTC, Josmar-jr commented
I took the CHANGELOG from the master branch and added the feat from this PR, right?
@ArthurTriis1

2024-07-17 18:57 UTC, ArthurTriis1 approved these changes

2024-07-17 18:59 UTC, merged