[B2BORG-97] Changes to B2B frontend component for adding vs editing user accounts
vtex-apps/b2b-organizations pull request #31
Opened 2022-04-26 19:46 UTC by arturmagalhaesjr

#### What problem is this solving?

It was created a mutation for addUser and updateUser, so this PR will change the frontend to those.

Environment:[ https://b2borg2--sandboxusdev.myvtex.com/]( https://b2borg2--sandboxusdev.myvtex.com/)

#### How to test it?

1) Login into store as Org Admin
2) Go to my account
3) My Organization
4) You will be able to add some users and see the mutation on the Networking tab

2022-04-27 20:21 UTC, polishq requested changes

2022-04-27 20:21 UTC, polishq commented on react/graphql/createOrganizationRequest.graphql
> -    status
Seems like this shouldn't be removed

2022-04-28 11:17 UTC, arturmagalhaesjr reviewed
done

2022-04-28 13:20 UTC, polishq approved these changes

2022-04-28 13:21 UTC, merged