Show trade polices as options in price table listing
vtex-apps/b2b-organizations pull request #32
Opened 2022-04-29 17:51 UTC by jonmast

#### What problem is this solving?

Trade policies (AKA sales channels) also act as pricing tables, but only
the main one is included in the priceTables query. Introduce an
additional query to fetch the data for those and include it in the
display. This required a bit of tweaking of the UI logic since trade
policies have a display name plus a numerical id vs just a string name
for the regular price channels.

#### How to test it?

I don't know if you can access it, but I've got it running in a workspace on the Whitebird store
[Workspace](https://witi167--whitebird.myvtex.com)

2022-04-29 18:07 UTC, polishq requested changes
Functionality looks great, but there are some lint errors that need to be fixed (don't worry about the warnings, just the errors). 

Also, please update CHANGELOG.md to describe what was changed (use the `### [Unreleased]` section near the top of the file).

2022-04-29 18:07 UTC, polishq commented on react/graphql/getSalesChannels.graphql
> +    id,
```suggestion
    id
```

2022-04-29 18:31 UTC, jonmast commented
Thanks for the review @polishq, I've made the requested changes.

2022-04-29 18:49 UTC, polishq commented
> Thanks for the review @polishq, I've made the requested changes.

Thanks! I'm talking to our QA team about these Cypress / SonarCloud failures, I believe those are just happening because the source branch is in an external repo. Further changes to the code should not be necessary.

2022-04-29 18:54 UTC, polishq submitted a review, later dismissed

2022-04-29 21:06 UTC, polishq commented
@jonmast We've fixed the SonarCloud issue, please rebase your branch and we should be good to go

2022-05-02 14:49 UTC, jonmast commented
@polishq Rebase is done

2022-05-02 15:08 UTC, polishq approved these changes

2022-05-02 15:13 UTC, merged

2022-05-02 15:17 UTC, polishq commented
Thanks @jonmast ! Version 1.8.0 was published successfully. We'll deploy it to all accounts later today but if you want to install it sooner, you can do so manually (`vtex install vtex.b2b-organizations@1.8.0`)